### ISSUE TITLE
about the speed contorller button disappear

### ISSUE THREAD

**Issue by dada1437903138** [ssssssander/youtube-more-speeds#1]
YouTube upgraded its UI several weeks ago, since then the video speed contorller button has gone. I guess this problem is caused by a change in the html layout, which can be easily fixed. I like this plugin so much, and expect a new version of it.

**Comment by ssssssander** [comment]
The issue has been fixed 😃.
Thanks so much for bringing this to my attention, and for using my script, I really appreciate it.

**Comment by ssssssander** [comment]
The previous fix was not quite it but now it should be fixed and live on Greasy Fork.

**Comment by Orr888** [comment]
Now same problem: The speed controller buttons has gone.
