### ISSUE TITLE
The speed controller buttons has gone.

### ISSUE THREAD

**Issue by Orr888** [ssssssander/youtube-more-speeds#2]
The speed controller buttons has gone.

**Comment by Orr888** [comment]
I checked, not working

**Comment by ElPioterro** [comment]
What do you mean, for me script is working perfectly

Regards ElPioterro!

śr., 16 lis 2022, 08:43 użytkownik ORUC QAFAROV ***@***.***>
napisał:

**Comment by Orr888** [comment]
Your script is beautiful, I thank you for your excellent work. I have been using your script for several years now. This is the most necessary thing among all the scripts that I use.
But to my great regret after the last update of my browser, it stopped working. More precisely, the speed buttons are gone. I also installed a non-stable version of the browser, but your script does not work there either.

My Notebook : HP Pavilion Sleekbook 15 PC 087F
Operating system: Arch Linux x86_64
Kernel: 6.0.6-arch1-1
CPU: Intel i5-3317U (4) @ 2.600GHz
GPU: NVIDIA GeForce 610M/710M/810M/820
Memory: 6GB
DE: GNOME 43.0

Browser 1: Google Chrome Version 107.0.5304.87 (Official build), (64 bit)
Browser 2: Google Chrome Version 109.0.5384.0 (Official build), dev (64 bit)
Tampermonkey 1: 4.18.0
Tampermonkey 2: BETA 4.19.6173

I checked on all versions, but unfortunately nothing happened.
Advise what to do, please.

Thank you ElPioterro.
Best regards Oruj.

**Comment by ssssssander** [comment]
Hi everyone, it gives me great pleasure knowing you all like using my script!
I will try to fix it for the latest YouTube layout as soon as possible. Darn YouTube and their constant design changes.

**Comment by Orr888** [comment]
Many thanks dear friend. You are beautiful.

**Comment by Orr888** [comment]
There is no 16x speed in the new script, why?
It was very helpful in rewinding the ads to keep the monetization of the bloger going.
If you update the script in the future, please add it.

Thank you so much.

**Comment by ElPioterro** [comment]
> There is no 16x speed in the new script, why?

You can check out original-fix branch: [here](https://github.com/ElPioterro/youtube-more-speeds/blob/original-fix/youtube-more-speeds.user.js) :)

> Why don't you update it in the Tampermonkey repository? Then no one would face such a problem.
> 
> Of course, I'm clumsy, and did not check the script from your github repository, but it would be prettier if you updated the script in the Tampermonkey repository. What do you think about this? ;)

In this repository I pulled request to fix this bug but it seems like Sander (author) didn't seen it yet.

**Comment by ElPioterro** [comment]
Yeah It does look better. 
Updated it and It's in original branch. 👍

**Comment by Orr888** [comment]
Thank you
