### ISSUE TITLE
Platform changes are not working 30/11/2022

### ISSUE THREAD

**Issue by steve007iii** [ssssssander/youtube-more-speeds#5]
Platform changes are not working 30/11/2022

**Comment by ssssssander** [comment]
It has been fixed :)

**Comment by nedz25** [comment]
Sorry for hijacking this topic, I'm wondering if it possible to convert this script so it can run on mobile web browser.
nb. I have no knowledge on coding, 
Thanks

**Comment by ssssssander** [comment]
> Sorry for hijacking this topic, I'm wondering if it possible to convert this script so it can run on mobile web browser.
> nb. 
> I have no knowledge on coding, 
> I use a web browser that runs userscripts without GM or Tamper Monkey.. 
> Thanks 

Hi! What mobile web browser are you using?

**Comment by nedz25** [comment]
I use a browser called Via.

**Comment by ssssssander** [comment]
> I use a browser called Via. 

How exactly can you run userscripts on this browser?

**Comment by nedz25** [comment]
I go to Settings >> scripts >> The + sign
and I copy the script inside.
I have a lot of scripts running successfully except the ones that needed the @grant or @require thing!

**Comment by grant** [comment]
What?

**Comment by ssssssander** [comment]
> I go to Settings >> scripts >> The + sign
> and I copy the script inside.
> I have a lot of scripts running successfully except the ones that needed the @grant or @require thing! 

I've found that the script works if you change the user-agent of your browser to Windows (Chrome) (Tools > User-agent).

**Comment by nedz25** [comment]
👍 it works, Thank you very much.
